# Render Blueprint
services:
  - type: web
    name: teslaplayer-server
    runtime: docker
    dockerfilePath: ./apps/server/Dockerfile
    dockerContext: ./apps/server
    envVars:
      - key: PORT
        value: 4000
      - key: WS_BASE_PORT
        value: 8081
      - key: CORS_ORIGINS
        sync: false
      - key: NODE_ENV
        value: production
